"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](#49fa0a)\
[ 󰍳 ](bg:#3fe002 fg:#090c0c)\
[](bg:#1f7000 fg:#3fe002)\
$directory\
[](fg:#1f7000 bg:#0e3002)\
$git_branch\
$git_status\
[](fg:#0e3002 bg:#071701)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#071701 bg:#365c28)\
$time\
[ ](fg:#365c28)\
\n$character"""

[directory]
style = "fg:#e3e5e5 bg:#1f7000"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#16380a"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#16380a"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[nodejs]
symbol = ""
style = "bg:#092101"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#092101"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#092101"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#092101"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#365c28"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
